### ISSUE TITLE
IndexError: Cannot choose from an empty sequence

### ISSUE THREAD

**Issue by Strykar** [fretboardfreak/kitty-theme-changer#6]
I'm unsure what I'm doing wrong, `kitty-theme-changer` was installed inside a Python Virtual Environment.
My config:
```
$ cat kittythemechanger.py
'''A config module for the Kitty Theme Changer Tool.'''''''''
from pathlib import Path
theme_dir = Path(' ~/.config/kitty/kitty-themes/themes').expanduser()
conf_dir = Path('~/.config/kitty').expanduser()
theme_link = conf_dir.joinpath('theme.conf')
light_theme_link = conf_dir.joinpath('light-theme.conf')
dark_theme_link = conf_dir.joinpath('dark-theme.conf')
socket = 'unix:/tmp/mykitty'
```
The instance of kitty I'm trying it in is started with `--listen-on=unix:/tmp/mykitty` and its loaded conf file includes `allow_remote_control socket-only`.
But when I try to `--list themes`, I get:
```
$ kitty-theme -c ../kittythemechanger.py --list
Traceback (most recent call last):
  File "./kitty-theme", line 11, in <module>
    load_entry_point('kitty-theme-changer==0.4', 'console_scripts', 'kitty-theme')()
  File "/home/strykar/kitty_py_venv/lib/python3.8/site-packages/kittytheme/kittytheme.py", line 56, in main
    check_symlinks(config)
  File "/home/strykar/kitty_py_venv/lib/python3.8/site-packages/kittytheme/kittytheme.py", line 171, in check_symlinks
    get_random_theme_config(config.theme_dir))
  File "/home/strykar/kitty_py_venv/lib/python3.8/site-packages/kittytheme/kittytheme.py", line 162, in get_random_theme_config
    return random.choice([i for i in theme_dir.glob('*conf')])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```

**Comment by fretboardfreak** [comment]
Thanks for providing a traceback. From the info in your ticket it looks like it read your config file just fine but was enable to find any theme files in the directory you sperified in the config. 

Did you download any theme configs into that directory?

Perhaps you could provide the full --debug and --verbose output and I can see if anything else shows up there.

**Comment by fretboardfreak** [comment]
I'll add an error message if no themes are found. It looks like it is trying to set up the symlinks it uses to switch the theme configs but it cannot find any theme files in the directory you have in the config file and is unable to.

**Comment by Strykar** [comment]
I have git pulled all of them, the themes do indeed exist under `~/.config/kitty/kitty-themes/themes/`

**Comment by fretboardfreak** [comment]
I have added a better message to that area of the code so it should now have a more user friendly message. It will be checked in after my testing and released soon.

I believe I have found exactly why you have received the error even though the directory exists and contains files.

If you look really closely at your configuration file the theme_dir path variable has a leading space character in the input string to the Path object.  In my testing this prevents the path from being recognized as a valid/existing posix path. 

```
In [1]: from pathlib import Path                     

In [2]: p = Path(' ~/Dropbox').expanduser()          

In [3]: p                 
Out[3]: PosixPath(' ~/Dropbox')

In [4]: p.exists()        
Out[4]: False
```

Please try removing that space in that variable and I believe the theme changer should then work for you.
